### ISSUE TITLE
ios 11 Issues

### ISSUE THREAD

**Issue by ercantulu** [priore/AVPlayerOverlay#3]
Player is not compatible with Ios 11. Overlay does not respond to touch.

**Comment by Anbu312** [comment]
Hi @ercantulu overlay issue fixed ?

**Comment by ercantulu** [comment]
try to add the overlay to contentOverlayView. That may help.

**Comment by Anbu312** [comment]
Hi Ercantulu 

Please send sample code. I don't understand overlay to contentOverlayView.

Thanks

Anbu

**Comment by Anbu312** [comment]
Ercantulu cool it's working now Thanks lot.

**Comment by icodecocoa** [comment]
Please send a sample code to me too. I am facing the same issue and really stuck for days on this.

**Comment by Anbu312** [comment]
Hi @icodecocoa 

Sorry for delay. Below sample code
**AVPlayerVC.m file**
Change below code
[self.view addSubview:_overlayVC.view]; replace to **[self.contentOverlayView addSubview:_overlayVC.view];**

**Comment by Anbu312** [comment]
Hi @ercantulu 

I am facing delay playing videos. anybody facing that issue. Below my code I load my video player to TableView give me any suggestion guys lot of helpful for me.

             cell.playerVC.videoURL = @"Video Url";
            cell.playerVC.overlayVC.view.tag = indexPath.row;
            [cell.playerVC.view setFrame:cell.feedImage.bounds];
            cell.playerVC.videoGravity = AVLayerVideoGravityResizeAspectFill;
            [((UIView *)cell.feedImage) addSubview:cell.playerVC.view];
            
            [[AVAudioSession sharedInstance]
             setCategory: AVAudioSessionCategoryPlayback
             error: nil];
