### ISSUE TITLE
Issue with playback on iOS 11

### ISSUE THREAD

**Issue by anishpandey** [priore/AVPlayerOverlay#4]
Cannot play videos for iOS 11

**Comment by Anbu312** [comment]
Hi @anishpandey you are fixed that issue ?

**Comment by anishpandey** [comment]
Hi Anbu
I haven't fixed the issue.  Not sure where is the problem. Even the sample
app has this issue.

I am using the player for m3u8 playback and offline playback.

Regards
Anish

**Comment by Anbu312** [comment]
Hi Anish

I have same problem. Player bottom bar not showing my side. I don't know how to fix that issue.

Thanks 
Anbu
