### ISSUE TITLE
Video not play iOS 11.Overlay does not respond to touch.Video play button not show

### ISSUE THREAD

**Issue by Anbu312** [priore/AVPlayerOverlay#5]

**Comment by yusadogru** [comment]
you can call addChildViewController and addSubview methods in viewDidAppear. I fixed it like this.

```
- (void)viewDidAppear:(BOOL)animated
{
   ..........
    
    [self addChildViewController:_overlayVC];
    [self.view addSubview:_overlayVC.view];
    [_overlayVC didMoveToParentViewController:self];
}
```

**Comment by ios-apps** [comment]
dispatch_async(dispatch_get_main_queue(), ^{
		if (_overlayStoryboardId.length > 0)
		{
			_overlayVC = [self.storyboard instantiateViewControllerWithIdentifier:_overlayStoryboardId];
			[_overlayVC loadSubtitlesWithURL:_subtitlesURL];

			[self addChildViewController:_overlayVC];
			[self.view addSubview:_overlayVC.view];
			[_overlayVC didMoveToParentViewController:self];

			[_overlayVC addTarget:self action:@selector(disableDealloc) forEvents:AVPlayerOverlayEventDidPIPBecomeActive];
			[_overlayVC addTarget:self action:@selector(enableDealloc) forEvents:AVPlayerOverlayEventDidPIPDeactivation];
			[_overlayVC addTarget:self action:@selector(didPeriodicTimeObserver:) forEvents:AVPlayerOverlayEventPeriodicTimeObserver];
		}

		if (_PIPStoryboardId.length > 0)
		{
			_pipOverlayVC = [self.storyboard instantiateViewControllerWithIdentifier:_PIPStoryboardId];

			[_pipOverlayVC addTarget:self action:@selector(enableDealloc) forEvents:AVPlayerOverlayEventPIPClosed];
			[_pipOverlayVC addTarget:_overlayVC action:@selector(pipDeactivate) forEvents:AVPlayerOverlayEventPIPDeactivationRequest];

			[self addChildViewController:_pipOverlayVC];
			[self.view addSubview:_pipOverlayVC.view];
			[_pipOverlayVC didMoveToParentViewController:self];

			[_overlayVC addTarget:_pipOverlayVC action:@selector(showControls) forEvents:AVPlayerOverlayEventDidPIPBecomeActive];
			[_overlayVC addTarget:_pipOverlayVC action:@selector(hideControls) forEvents:AVPlayerOverlayEventWillPIPDeactivation];
		}
    });

**Comment by Anbu312** [comment]
Hi @yusadogru @ios-apps 

I am facing delay playing videos. anybody facing that issue. Below my code I load my video player to TableView give me any suggestion guys lot of helpful for me.

                 cell.playerVC.videoURL = @"Video Url";
                cell.playerVC.overlayVC.view.tag = indexPath.row;
                [cell.playerVC.view setFrame:cell.feedImage.bounds];
                cell.playerVC.videoGravity = AVLayerVideoGravityResizeAspectFill;
                [((UIView *)cell.feedImage) addSubview:cell.playerVC.view];
                
                [[AVAudioSession sharedInstance]
                 setCategory: AVAudioSessionCategoryPlayback
                 error: nil];

**Comment by Anbu312** [comment]
Hi @ios-apps @yusadogru 

Video button now show Thanks for support but Video playing delay.

Video Button show sample code

**AVPlayerVC.m file**
Change below code
[self.view addSubview:_overlayVC.view]; replace to **[self.contentOverlayView addSubview:_overlayVC.view];**

It's working fine.

**Comment by ios-apps** [comment]
Do you remove an old player from the cell before addSubview:?

**Comment by Anbu312** [comment]
Hi @ios-apps 

Thanks for response.

Actually My tableview load images and videos. cellForRowAtIndexPath check image or video. Video means add  **[((UIView )cell.feedImage) addSubview:cell.playerVC.view];** Image means **[cell.playerVC.view removeFromSuperview];**.

**Comment by ios-apps** [comment]
If the cell has already a player, you will add another one, and so on. Each cell will have a few players and your app will be slow, finally it will crash. 
Set a tag to the player, for example 100 and 101 for the image. Find the assert by the tag and remove it before adding the new assert.

UIImageView *imageView  = (UIImageView *)[cell viewWithTag:101];
[imageView removeFromSuperview];

**Comment by Anbu312** [comment]
Thanks @ios-apps. I will try and revert you.
